apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASS: {{ .Values.secrets.DB_PASS | quote }}