image:
  repository: myacr12067.azurecr.io/web-app
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

probes:
  path: /health
  port: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 50

# Non-secret env (key: value)
env: {}

# Secret keys (values are NOT stored here; create the Secret in the cluster)
secretEnv: {}
